require('core.plugin_config.treesitter')
require('core.plugin_config.lua-line')
require('core.plugin_config.nvim-tree')
require('core.plugin_config.telescope')
require('core.plugin_config.completions')
require('core.plugin_config.lsp_zero')
-- require('core.plugin_config.lsp')
require('core.plugin_config.fugitive')
require('core.plugin_config.comment')
require('core.plugin_config.cmp')
require('core.plugin_config.orgmode')
require('core.plugin_config.copilot')
require('core.plugin_config.refactoring')
require('core.plugin_config.neotest')
